version: '3.7'

services:
  btm-mysql:
    container_name: btm-mysql-prod
    ports:
      - '33061:3306'
  btm-php:
    container_name: btm-php-prod
    environment:
      APP_ENV: prod
      APP_VERSION: prod
      DATABASE_URL: mysql://root:@btm-mysql:3306/btm_prod

  btm-nginx:
    container_name: btm-nginx-prod
    ports:
      - '8081:80'
